version: "3"
services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8181:8080
    volumes:
      - /mnt/hdd:/data
      - ./:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always

networks:
  default:
    external:
      name: pi-net
