version: "2.1"
services:
  nzbhydra2:
    image: linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - ./nzbhydra2:/config
      - /mnt/hdd/downloads/torrent:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - ./:/config
      - /mnt/hdd/downloads/torrent:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorent:/config
      - /mnt/hdd/downloads/torrent:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

networks:
  default:
    external:
      name: pi-net
